import json
import re


class CommunicationAnalysisService:

    def __init__(self):
        self.filler_words = [
            "um",
            "uh",
            "like",
            "actually",
            "basically",
            "you know",
            "i mean",
            "kind of",
            "sort of"
        ]
    import json
import re
from collections import Counter


class CommunicationAnalysisService:
    """
    Service to analyze interview transcript generated by Whisper.

    Features:
    - Word Count
    - Sentence Count
    - Speaking Duration
    - Words Per Minute (WPM)
    - Filler Word Detection
    - Vocabulary Richness
    """

    def __init__(self):
        self.filler_words = [
            "um",
            "uh",
            "like",
            "actually",
            "basically",
            "you know",
            "i mean",
            "kind of",
            "sort of",
            "hmm",
            "ah"
        ]

    # -----------------------------
    # Load Transcript JSON
    # -----------------------------
    def load_transcript(self, transcript_path):
        with open(transcript_path, "r", encoding="utf-8") as file:
            data = json.load(file)

        return data

    # -----------------------------
    # Count Words
    # -----------------------------
    def get_word_count(self, text):
        words = re.findall(r"\b\w+\b", text)
        return len(words)

    # -----------------------------
    # Count Sentences
    # -----------------------------
    def get_sentence_count(self, text):
        sentences = re.split(r"[.!?]+", text)
        sentences = [s.strip() for s in sentences if s.strip()]
        return len(sentences)

    # -----------------------------
    # Speaking Duration
    # -----------------------------
    def get_duration(self, segments):
        if not segments:
            return 0

        return round(segments[-1]["end"], 2)

    # -----------------------------
    # Words Per Minute
    # -----------------------------
    def get_words_per_minute(self, total_words, duration_seconds):

        if duration_seconds == 0:
            return 0

        minutes = duration_seconds / 60

        return round(total_words / minutes, 2)

    # -----------------------------
    # Average Sentence Length
    # -----------------------------
    def get_average_sentence_length(self, text):

        sentence_count = self.get_sentence_count(text)

        if sentence_count == 0:
            return 0

        total_words = self.get_word_count(text)

        return round(total_words / sentence_count, 2)

    # -----------------------------
    # Vocabulary Richness
    # -----------------------------
    def get_vocabulary_score(self, text):

        words = re.findall(r"\b\w+\b", text.lower())

        if not words:
            return 0

        unique_words = len(set(words))

        return round(unique_words / len(words), 2)

    # -----------------------------
    # Filler Word Analysis
    # -----------------------------
    def get_filler_word_analysis(self, text):

        text = text.lower()

        filler_counts = {}

        total_fillers = 0

        for filler in self.filler_words:

            count = text.count(filler)

            filler_counts[filler] = count

            total_fillers += count

        return total_fillers, filler_counts

    # -----------------------------
    # Most Frequently Used Words
    # -----------------------------
    def get_top_words(self, text, top_n=10):

        words = re.findall(r"\b\w+\b", text.lower())

        stop_words = {
            "the", "a", "an", "is", "are", "was", "were",
            "to", "of", "and", "in", "on", "at", "for",
            "i", "you", "we", "it", "that", "this",
            "my", "your", "our", "me", "he", "she",
            "they", "be", "have", "has", "had", "do",
            "does", "did", "with", "as", "but"
        }

        filtered_words = [
            word for word in words
            if word not in stop_words
        ]

        counter = Counter(filtered_words)

        return dict(counter.most_common(top_n))

    # -----------------------------
    # Complete Analysis
    # -----------------------------
    def analyze(self, transcript_path):

        data = self.load_transcript(transcript_path)

        text = data.get("text", "")

        segments = data.get("segments", [])

        total_words = self.get_word_count(text)

        sentence_count = self.get_sentence_count(text)

        duration = self.get_duration(segments)

        wpm = self.get_words_per_minute(
            total_words,
            duration
        )

        avg_sentence_length = self.get_average_sentence_length(
            text
        )

        vocabulary_score = self.get_vocabulary_score(
            text
        )

        filler_total, filler_breakdown = self.get_filler_word_analysis(
            text
        )

        top_words = self.get_top_words(text)

        return {

            "language": data.get("language", "Unknown"),

            "word_count": total_words,

            "sentence_count": sentence_count,

            "duration_seconds": duration,

            "words_per_minute": wpm,

            "average_sentence_length": avg_sentence_length,

            "vocabulary_score": vocabulary_score,

            "total_filler_words": filler_total,

            "filler_word_breakdown": filler_breakdown,

            "top_words": top_words
        }